/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';

export const ID_FUNKY_FALCON = 'FUNKY_FALCON';

export const CanFunkyFalcon = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF('models/funky_falcon.glb');

  return (
    <group name={ID_FUNKY_FALCON} {...props} dispose={null} ref={ref}>
      <group scale={8}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials.CanMat}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001_1.geometry}
          material={materials.FUNKY_FALCON}
        />
      </group>
    </group>
  );
});

useGLTF.preload('models/funky_falcon.glb');
